app:
  cors:
    allowedOrigins:
      - http://localhost:3000
      - http://localhost:5173
    allowedMethods:
      - GET
      - POST
      - PUT
      - DELETE
    allowedHeaders:
      - Authorization
      - Content-Type
      - "X-XSRF-TOKEN"
    allowCredentials: true
  jwt:
    accessTokenExpirationMs: 900000
    refreshTokenExpirationMs: 604800000
    secretKey: sR8Fd4ro3vLDlC0e94vvJDNJ8AqD7pGtoyqxxebvDEU

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=cinemax
    username: postgres
    password: password
