server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: cinemax-application
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/db.changelog-master.xml
    default-schema: cinemax
    enabled: true
